title: Xinran Yang's Homepage
page-top-title: Xinran Yang
top-section-bg-text: Computer Science
home-subtitle: Xinran Yang&ensp;|&ensp;杨欣然
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
